# Generated by Django 4.2.1 on 2023-05-31 01:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ctu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Dob', models.DateTimeField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=13)),
                ('File', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
