# Generated by Django 4.2.1 on 2023-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ctu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctu',
            name='File',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='file/'),
        ),
    ]
